services:
  node:
    build:
      context: ./config/node_js
      dockerfile: Dockerfile
    container_name: camagru_node_app
    env_file:
      - .env
    volumes:
      - ./app/node:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${NODE_PORT}:${NODE_PORT}" # si necesitas acceder desde fuera
    networks:
      - camagru_network

  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    container_name: camagru_php
    env_file:
      - .env
    networks:
      - camagru_network
    volumes:
      - ./app/public:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "${PHP_PORT}:${PHP_PORT}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  mongodb:
    build:
      context: ./config/mongo
      dockerfile: Dockerfile
    container_name: camagru_mongodb
    env_file:
      - .env
    networks:
      - camagru_network
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo-express:
    image: mongo-express:latest
    container_name: camagru_mongo_express
    env_file:
      - .env
    networks:
      - camagru_network
    ports:
      - "${ME_EXPRESS_PORT}:${ME_EXPRESS_PORT}"
    depends_on:
      - mongodb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  postgre:
    build:
      context: ./config/postgre
      dockerfile: Dockerfile
    container_name: camagru_postgres
    env_file:
      - .env
    networks:
      - camagru_network
      # volumes:
      # - ./data/postgre:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:${PG_PORT}"
    restart: unless-stopped
    environment:
      POSTGRES_USER: camagru
      POSTGRES_PASSWORD: camagru
      POSTGRES_DB: camagru_db

  python:
    build:
      context: ./config/python
      dockerfile: Dockerfile
    container_name: camagru_python
    env_file:
      - .env
    networks:
      - camagru_network
    volumes:
      - ./app/public:/var/www/html
    ports:
      - "${PYTHON_PORT}:${PYTHON_PORT}"
    restart: unless-stopped

  nginx:
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    container_name: camagru_nginx
    networks:
      - camagru_network
    env_file:
      - .env
    volumes:
      - ./app/public:/var/www/html
    ports:
      - "${APP_PORT}:80"
    restart: unless-stopped
    depends_on:
      - php
      - node
      - python

networks:
  camagru_network:
    driver: bridge
