services:
  nginx:
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    container_name: camagru_nginx
    networks:
      - camagru_network
    env_file:
      - .env
    volumes:
      - ./app/public:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - php

  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    container_name: camagru_php
    env_file:
      - .env
    networks:
      - camagru_network
    volumes:
      - ./app/public:/var/www/html
      #- ./config:/var/www/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9006:9005"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  mongodb:
    build:
      context: ./config/mongo
      dockerfile: Dockerfile
    container_name: camagru_mongodb
    env_file:
      - .env
    networks:
      - camagru_network
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo-express:
    image: mongo-express:latest
    container_name: camagru_mongo_express
    env_file:
      - .env
    networks:
      - camagru_network
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  postgre:
    build:
      context: ./config/postgre
      dockerfile: Dockerfile
    container_name: camagru_postgres
    env_file:
      - .env
    networks:
      - camagru_network
    volumes:
      - ./data/postgre:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: camagru
      POSTGRES_PASSWORD: camagru
      POSTGRES_DB: camagru_db
  python:
    build:
      context: ./config/python
      dockerfile: Dockerfile
    container_name: camagru_python
    env_file:
      - .env
    networks:
      - camagru_network
    volumes:
      - ./app/public:/var/www/html
    ports:
      - "6000:6000"
    restart: unless-stopped

networks:
  camagru_network:
    driver: bridge
