version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: camagru_nginx
    networks:
      - camagru_network
    volumes:
      - ./app/public:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    restart: unless-stopped
  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html
    restart: unless-stopped
networks:
  camagru_network:
    driver: bridge
volumes:
  camagru_data:
    driver: local
