FROM  mongo:latest

# Use the official MongoDB image as a base
# Set the working directory
WORKDIR /data/mongodb

# Expose the default MongoDB port

EXPOSE $MONGODB_PORT

#CMD [ "docker-entrypoint.js", $MONGODB_SERVER ]